export const artists = [
    "NSync",
    "Backstreet Boys",
    "Savage Garden",
    "Warrant",
    "Boston",
    "Foreigner",
    "Chicago",
    "Kansas",
    "Styx",
    "Michael Jackson",
    "John Mayer",
    "Metallica",
    "Disturbed",
    "Phil Collins",
    "Genesis",
    "Hootie & The Blowfish",
    "Darius Rucker",
    "Laura Brannagin",
    "Mariah Carey",
    "Beyonce",
    "Rihanna",
    "Sugar Ray",
    "Def Leppard",
    "Goo Goo Dolls",
    "Red Hot Chili Peppers",
];

